---

# Monitor Number    = #$34T#

#  - name: "CUCM Config: Interactive Voice Response"
#    hosts: cucm
#    gather_facts: no
#    become: yes
#    tasks: 
      - name: "Assigning Dial Peer"
        ios_command:
          commands: 
            - config t
            - dial-peer voice 69 voip
            - service rivanaa out-bound
            - "destination-pattern #$34T#69"
            - "session target ipv4:10.#$34T#.100.8"
            - "incoming called-number #$34T#69"
            - dtmf-relay h245-alphanumeric
            - codec g711ulaw
            - no vad
            - end
        tags:
          - dial
      
      - name: "Specifying Music on Hold"
        ios_command:
          commands: 
            - config t
            - telephony-service
            - 'moh "flash:/en_bacd_music_on_hold.au"'
            - end
        tags:
          - moh
      
      - name: "Setting Application Parameters"
        ios_command:
          commands: 
            - config t
            - application
            - "service rivanaa flash:app-b-acd-aa-3.0.0.2.tcl"
            - paramspace english index 1        
            - param number-of-hunt-grps 2
            - param dial-by-extension-option 8
            - param handoff-string rivanaa
            - "param welcome-prompt flash:en_bacd_welcome.au"
            - paramspace english language en
            - param call-retry-timer 15
            - param service-name rivanqueue
            - "paramspace english location flash:"
            - param second-greeting-time 60
            - param max-time-vm-retry 2
            - param voice-mail 1234
            - param max-time-call-retry 700
            - "param aa-pilot #$34T#69"
            - "service rivanqueue flash:app-b-acd-3.0.0.2.tcl"
            - param queue-len 15
            - "param aa-hunt1 #$34T#00"
            - "param aa-hunt2 #$34T#01"
            - "param aa-hunt3 #$34T#77"
            - "param aa-hunt4 #$34T#33"
            - param queue-manager-debugs 1
            - param number-of-hunt-grps 4
            - end
        tags: 
          - app
